// Generated by CoffeeScript 1.10.0
angular.module('leninPhotographyApp').config(function($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise("/home");
  return $stateProvider.state('home', {
    url: '/home',
    templateUrl: "views/main.html",
    controller: 'homeCtrl'
  }).state('details', {
    url: '/photo/:id',
    templateUrl: "views/partials/photo_details.html",
    controller: 'photoDetailCtrl'
  }).state('about', {
    url: '/about',
    templateUrl: "views/partials/about.html"
  }).state('contact', {
    url: '/contact',
    templateUrl: "views/partials/contact.html"
  });
});
